name: Build APK with Custom Docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build using custom Docker image
      run: |
        # Создаем Dockerfile на лету
        cat > Dockerfile << 'EOF'
        FROM ubuntu:22.04
        
        # Установка зависимостей
        RUN apt-get update && apt-get install -y \
            python3 python3-pip python3-venv git zip unzip \
            openjdk-17-jdk autoconf automake libtool pkg-config \
            zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 \
            cmake libffi-dev libssl-dev libjpeg-dev libpng-dev
        
        # Установка Buildozer и Kivy
        RUN pip3 install buildozer kivy cython
        
        WORKDIR /src
        EOF
        
        # Собираем и запускаем
        docker build -t buildozer-image .
        docker run --rm \
          -v "$PWD":/src \
          buildozer-image \
          sh -c "
            buildozer init || true &&
            buildozer -v android debug
          "

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-app
        path: bin/*.apk
