name: Build APK with Docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build with Docker
      run: |
        # Скачиваем и запускаем готовый образ
        docker pull kivy/buildozer:latest
        
        docker run --rm \
          -v "$(pwd)":/src \
          -w /src \
          kivy/buildozer:latest \
          sh -c "
            buildozer init &&
            buildozer -v android debug
          "

    - name: Check build results
      run: |
        echo "Generated files:"
        ls -la bin/ || true
        find . -name "*.apk" | head -5

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-app
        path: bin/*.apk
        if-no-files-found: warn

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: .buildozer
