name: Build Kivy APK - With Debug

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Initial debug
      run: |
        echo "=== INITIAL DEBUG ==="
        echo "Workspace: $GITHUB_WORKSPACE"
        echo "Runner OS: $RUNNER_OS"
        echo "Python version: $(python --version 2>&1 || echo 'No Python')"
        echo "Current dir: $(pwd)"
        ls -la

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip openjdk-17-jdk \
          autoconf automake libtool pkg-config \
          zlib1g-dev libncurses5-dev libncursesw5-dev \
          libtinfo5 cmake libffi-dev libssl-dev

    - name: Debug Java and Android tools
      run: |
        echo "=== JAVA AND ANDROID DEBUG ==="
        java -version
        javac -version
        which aidl || echo "aidl not found - this is the problem!"
        
        # Поиск aidl в системе
        echo "Searching for aidl:"
        find /usr -name "aidl" 2>/dev/null || true
        find /opt -name "aidl" 2>/dev/null || true
        find ~ -name "aidl" 2>/dev/null || true

    - name: Install Python packages
      run: |
        pip install buildozer kivy cython

    - name: Debug Python packages
      run: |
        echo "=== PYTHON PACKAGES DEBUG ==="
        python -c "import buildozer; print('Buildozer installed')" || echo "Buildozer import failed"
        python -c "import kivy; print('Kivy version:', kivy.__version__)" || echo "Kivy import failed"
        buildozer --version || echo "Buildozer command failed"

    - name: Try to install aidl manually
      run: |
        echo "=== MANUAL AIDL INSTALL ==="
        # Попытка установить aidl
        sudo apt-get install -y android-sdk-build-tools || \
        echo "Cannot install android-sdk-build-tools"
        
        # Поиск альтернативных репозиториев
        sudo apt-cache search aidl || echo "No aidl packages found"

    - name: Build APK with timeout
      run: |
        echo "=== STARTING BUILD ==="
        timeout 1800 buildozer -v android debug || \
        echo "Build timed out or failed"

    - name: Find and collect APK files
      run: |
        echo "=== FINDING APK FILES ==="
        find . -name "*.apk" -type f 2>/dev/null | head -10 || echo "No APK files found"
        ls -la bin/ 2>/dev/null || echo "No bin directory"
        find .buildozer -name "*.apk" -type f 2>/dev/null | head -5 || echo "No APK in .buildozer"

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk-file
        path: |
          bin/*.apk
          .buildozer/android/platform/build-*/dists/*/build/outputs/apk/*.apk
        if-no-files-found: ignore

    - name: Upload build logs
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          .buildozer
          buildozer.spec
        if-no-files-found: ignore
