name: Build Kivy APK - Fixed Non-Interactive

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build with auto-confirm
      run: |
        docker run --rm \
          -v "$PWD":/src \
          -w /src \
          python:3.9-slim-bullseye \
          sh -c "
            # Устанавливаем зависимости
            apt-get update
            apt-get install -y \
              git zip unzip openjdk-17-jdk \
              autoconf automake libtool pkg-config \
              zlib1g-dev libncurses5-dev libncursesw5-dev \
              libtinfo5 cmake libffi-dev libssl-dev \
              python3-dev libjpeg-dev libpng-dev
            
            # Устанавливаем Python пакеты
            pip install buildozer kivy cython
            
            # Автоматически подтверждаем все запросы
            echo 'y' | buildozer init 2>/dev/null || true
            
            # Собираем без интерактивности
            buildozer -v android debug --non-interactive
          "

    - name: Check build results
      run: |
        echo "=== BUILD RESULTS ==="
        ls -la bin/ 2>/dev/null || echo "No bin directory"
        find . -name "*.apk" 2>/dev/null | head -5 || echo "No APK files found"

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-app
        path: |
          bin/*.apk
          .buildozer/android/platform/build-*/dists/*/build/outputs/apk/*.apk
        if-no-files-found: ignore

    - name: Upload logs for debugging
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: .buildozer
