name: Build Kivy APK with Docker

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build with Docker non-interactive
      run: |
        docker run --rm \
          -v "$PWD":/src \
          -w /src \
          python:3.9-slim-bullseye \
          sh -c "
            apt-get update && \
            apt-get install -y \
              git zip unzip openjdk-17-jdk \
              autoconf automake libtool pkg-config \
              zlib1g-dev libncurses5-dev libtinfo5 \
              cmake libffi-dev libssl-dev && \
            pip install buildozer kivy cython && \
            buildozer init || true && \
            buildozer -v android debug --non-interactive
          "

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: kivy-apk
        path: bin/*.apk
        if-no-files-found: warn
