name: Build Kivy APK - Robust

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Clean up apt sources
      run: |
        # Удаляем проблемные репозитории
        sudo rm -f /etc/apt/sources.list.d/*microsoft* || true
        sudo rm -f /etc/apt/sources.list.d/*azure* || true
        
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Update package lists
      run: sudo apt-get update

    - name: Install essential packages
      run: |
        sudo apt-get install -y \
          software-properties-common \
          build-essential \
          git \
          zip \
          unzip

    - name: Install Java
      run: |
        sudo apt-get install -y openjdk-17-jdk
        echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-$(dpkg --print-architecture)" >> $GITHUB_ENV

    - name: Install build dependencies
      run: |
        sudo apt-get install -y \
          autoconf \
          automake \
          libtool \
          pkg-config \
          cmake \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          libffi-dev \
          libssl-dev \
          libjpeg-dev \
          libpng-dev

    - name: Install Python tools
      run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install cython==0.29.33
        pip install buildozer
        pip install kivy

    - name: Initialize Buildozer if needed
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Check build results
      run: |
        echo "Checking for APK files..."
        find . -name "*.apk" -type f | head -10 || echo "No APK files found"
        ls -la bin/ || true
        ls -la .buildozer/android/platform/build-*/dists/*/build/outputs/apk/ || true

    - name: Upload APK artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: |
          bin/*.apk
          .buildozer/android/platform/build-*/dists/*/build/outputs/apk/*.apk

    - name: Upload build logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          .buildozer
          buildozer.spec
