name: Build Kivy APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          autoconf \
          automake \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo6 \          # ЗДЕСЬ ИСПРАВЛЕНИЕ!
          cmake \
          libffi-dev \
          libssl-dev \
          python3-dev \
          libjpeg-dev \
          libpng-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython==0.29.33
        pip install buildozer
        pip install kivy

    - name: Initialize Buildozer
      run: |
        buildozer init || true

    - name: Build APK with Buildozer
      run: |
        buildozer -v android debug

    - name: List generated files
      run: |
        ls -la bin/ || true
        ls -la .buildozer/ || true

    - name: Upload APK artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: kivy-app-apk
        path: bin/*.apk

    - name: Upload build logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          .buildozer
          buildozer.spec
